// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZCYRg0Y6kJS7YtZRVv3zcaj3yLVKWdHc',
    appId: '1:707659684985:web:14a57d523a4c117a2888a8',
    messagingSenderId: '707659684985',
    projectId: 'connect-firebase-3cc0d',
    authDomain: 'connect-firebase-3cc0d.firebaseapp.com',
    storageBucket: 'connect-firebase-3cc0d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPz2HMeGrmuRKY3MeHpY7ku79XXsXsMyI',
    appId: '1:707659684985:android:ed1ae877d98c7a242888a8',
    messagingSenderId: '707659684985',
    projectId: 'connect-firebase-3cc0d',
    storageBucket: 'connect-firebase-3cc0d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE77WQ5SUES2TAPR6Zch8tJyrBH2S9JgA',
    appId: '1:707659684985:ios:a126c7697aabec722888a8',
    messagingSenderId: '707659684985',
    projectId: 'connect-firebase-3cc0d',
    storageBucket: 'connect-firebase-3cc0d.appspot.com',
    iosClientId: '707659684985-7pn3b2ipq88rrj7i2ahekfijav3odfqi.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
